# Generated by Django 5.2.5 on 2025-09-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
    ]
