# Generated by Django 5.2.5 on 2025-10-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address (must be unique)', max_length=254, unique=True),
        ),
    ]
