# Generated by Django 5.2.5 on 2025-10-03 02:01

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_options_project_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STCAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('use_monte_carlo', models.BooleanField(default=False)),
                ('monte_carlo_iterations', models.IntegerField(default=1000)),
                ('results_file', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stc_analyses', to='projects.project')),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
