# Generated by Django 5.2.5 on 2025-10-03 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stcanalysis',
            name='branch_analyzed',
            field=models.CharField(blank=True, help_text='Git branch analyzed', max_length=100),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='contributors_count',
            field=models.IntegerField(default=0, help_text='Number of contributors analyzed'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='coordination_actuals_total',
            field=models.IntegerField(default=0, help_text='Total actual coordination activities'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='coordination_requirements_total',
            field=models.IntegerField(default=0, help_text='Total coordination requirements'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='files_count',
            field=models.IntegerField(default=0, help_text='Number of files analyzed'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='missed_coordination_count',
            field=models.IntegerField(default=0, help_text='Number of missed coordination opportunities'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='stc_value',
            field=models.FloatField(blank=True, help_text='STC value (0-1, higher means better coordination)', null=True),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='tnm_output_dir',
            field=models.CharField(blank=True, help_text='TNM output directory used', max_length=500),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='unnecessary_coordination_count',
            field=models.IntegerField(default=0, help_text='Number of unnecessary coordination activities'),
        ),
        migrations.AlterField(
            model_name='stcanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
