# Generated by Django 5.2.5 on 2025-10-03 11:34

import uuid
from django.db import migrations, models


def convert_id_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        "ALTER TABLE stc_analysis_stcanalysis DROP COLUMN id CASCADE;"
    )
    schema_editor.execute(
        "ALTER TABLE stc_analysis_stcanalysis "
        "ADD COLUMN id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;"
    )
    schema_editor.execute(
        "ALTER TABLE stc_analysis_stcanalysis ALTER COLUMN id DROP DEFAULT;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stc_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stcanalysis',
            name='branch_analyzed',
            field=models.CharField(blank=True, help_text='Git branch analyzed', max_length=100),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='contributors_count',
            field=models.IntegerField(default=0, help_text='Number of contributors analyzed'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='coordination_actuals_total',
            field=models.IntegerField(default=0, help_text='Total actual coordination activities'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='coordination_requirements_total',
            field=models.IntegerField(default=0, help_text='Total coordination requirements'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='files_count',
            field=models.IntegerField(default=0, help_text='Number of files analyzed'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='missed_coordination_count',
            field=models.IntegerField(default=0, help_text='Number of missed coordination opportunities'),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='stc_value',
            field=models.FloatField(blank=True, help_text='STC value (0-1, higher means better coordination)', null=True),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='tnm_output_dir',
            field=models.CharField(blank=True, help_text='TNM output directory used', max_length=500),
        ),
        migrations.AddField(
            model_name='stcanalysis',
            name='unnecessary_coordination_count',
            field=models.IntegerField(default=0, help_text='Number of unnecessary coordination activities'),
        ),
        # PostgreSQL cannot cast bigint to uuid directly via ALTER COLUMN.
        # SeparateDatabaseAndState lets Django's state tracker record the UUID
        # field type (state_operations) while the database side drops and
        # recreates the column using compatible SQL (database_operations).
        # This is safe because the table has no data at this point in the
        # migration chain (created in 0001, nothing inserts before 0002 runs).
        # Databases that already have both 0001 and 0002 applied will skip this
        # entirely because Django sees the migration as already complete.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stcanalysis',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    convert_id_to_uuid,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
    ]
