# Generated by Django 5.2.5 on 2025-09-29 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Project description', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_risk_check_at',
            field=models.DateTimeField(blank=True, help_text='Last risk assessment timestamp', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mcstc_risk_score',
            field=models.FloatField(default=0.0, help_text='MC-STC risk score (0-1, higher means more risky)'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_type',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('other', 'Other')], default='github', help_text='Repository type', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='stc_risk_score',
            field=models.FloatField(default=0.0, help_text='STC risk score (0-1, higher means more risky)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_branch',
            field=models.CharField(blank=True, help_text='Default branch name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(max_length=255, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'git', 'ssh'])]),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('reviewer', 'Reviewer')], default='reviewer', help_text='Member role in the project', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['repo_type'], name='projects_pr_repo_ty_7ee0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deleted_at'], name='projects_pr_deleted_4c0d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['stc_risk_score'], name='projects_pr_stc_ris_af5ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['mcstc_risk_score'], name='projects_pr_mcstc_r_2d6fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['last_risk_check_at'], name='projects_pr_last_ri_cfe02a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner_profile', 'deleted_at'], name='projects_pr_owner_p_d8e6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['repo_type', 'deleted_at'], name='projects_pr_repo_ty_6ecff2_idx'),
        ),
    ]
