# Generated by Django 5.2.5 on 2025-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_stc_ris_af5ed6_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_mcstc_r_2d6fbe_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mcstc_risk_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stc_risk_score',
        ),
        migrations.AlterField(
            model_name='project',
            name='last_risk_check_at',
            field=models.DateTimeField(blank=True, help_text='Last risk assessment timestamp (legacy field)', null=True),
        ),
    ]
