# Generated by Django migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_projects_pr_stc_ris_af5ed6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_path',
            field=models.CharField(
                blank=True,
                help_text='Local path to cloned repository',
                max_length=500,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_run_stc',
            field=models.BooleanField(
                default=False,
                help_text='Automatically run STC analysis after TNM completion'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_run_mcstc',
            field=models.BooleanField(
                default=False,
                help_text='Automatically run MC-STC analysis after TNM completion'
            ),
        ),
    ]
