# Generated by Django 5.2.5 on 2025-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmonitoring',
            name='top_coordination_pairs',
            field=models.JSONField(blank=True, default=list, help_text='Top 10 coordination pairs with highest MC-STC impact'),
        ),
    ]
