# Generated by Django 5.2.5 on 2025-09-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author_contributor',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='project',
        ),
        migrations.DeleteModel(
            name='CodeFile',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
