# Generated by Django 5.2.5 on 2025-10-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_remove_commit_author_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributor',
            name='functional_role',
            field=models.CharField(choices=[('developer', 'Developer'), ('security', 'Security'), ('ops', 'Operations'), ('unclassified', 'Unclassified')], default='unclassified', help_text='Functional role for MC-STC calculation', max_length=20),
        ),
    ]
